[Editor] Grabcut
ingedata-ph/rhymes_annotation_engine pull request #106
Opened 2020-08-30 21:47 UTC by Knighto05

- Implement accuracy in selection

2020-08-31 11:00 UTC, rcserrano06 requested changes

2020-08-31 11:00 UTC, rcserrano06 commented on app/javascript/packs/styles/grabcut.scss
> +li.disabled {
scope style  as this will affect all elements on the DOM

2020-08-31 11:00 UTC, rcserrano06 commented on app/javascript/editor/modes/image_shape/create/polygon.create.ts
> +    document
use `document.getElementById` when dealing with IDs

2020-08-31 11:00 UTC, rcserrano06 commented on app/javascript/packs/styles/grabcut.scss
> +li.disabled {
scope your style as this might affect other elements as this is considered global.

2020-08-31 13:57 UTC, Knighto05 commented on app/javascript/editor/modes/image_shape/create/polygon.create.ts
> +    document
Okay, I changed some of them but I don't fully understand the difference between `getElementById` and `querySelector` even though I did some research.

2020-08-31 14:04 UTC, jrreyes29 commented on app/javascript/editor/modes/image_shape/create/polygon.create.ts
> +    document
the query selector will depend what do you get from the document and will get the FIRST element match, the different with the id will get the element direct with that id, and in the future, if that query is repeated in the document and you put before this one will you have issues.(normally the id is not repeated)

2020-09-01 03:04 UTC, jrreyes29 approved these changes

2020-09-01 03:04 UTC, merged